theme: jekyll-theme-minimal
title: antoinedme
description: Antoine de Marassé
logo: /assets/img/logo.png
#show_downloads: ["true" or "false" to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]
