theme: jekyll-theme-minimal
description: Hi there, I'm Antoine de Marassé. Web programming (dashboards), Machine Learning (using Sci-kit) or some interesting pieces of technology I love, here is where I will share some work!
logo: /assets/img/logo.png
#show_downloads: ["true" or "false" to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]
