theme: jekyll-theme-minimal
title: Antoine de Marassé
description: Trying to showcase some of my latest work.
logo: /assets/img/logo.png
#show_downloads: ["true" or "false" to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]
